# Generated by Django 2.0.5 on 2018-05-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='img1',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
