# Generated by Django 2.0.5 on 2018-05-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articles_img1'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='img2',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
