# Generated by Django 2.0.5 on 2018-05-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20180516_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='img0cap',
            field=models.CharField(default='caption', max_length=500),
        ),
        migrations.AddField(
            model_name='articles',
            name='img1cap',
            field=models.CharField(default='caption', max_length=500),
        ),
        migrations.AddField(
            model_name='articles',
            name='img2cap',
            field=models.CharField(default='caption', max_length=500),
        ),
        migrations.AddField(
            model_name='articles',
            name='img3cap',
            field=models.CharField(default='caption', max_length=500),
        ),
        migrations.AddField(
            model_name='articles',
            name='img4cap',
            field=models.CharField(default='caption', max_length=500),
        ),
        migrations.AddField(
            model_name='articles',
            name='img5cap',
            field=models.CharField(default='caption', max_length=500),
        ),
        migrations.AddField(
            model_name='articles',
            name='img6cap',
            field=models.CharField(default='caption', max_length=500),
        ),
        migrations.AddField(
            model_name='articles',
            name='img7cap',
            field=models.CharField(default='caption', max_length=500),
        ),
        migrations.AddField(
            model_name='articles',
            name='img8cap',
            field=models.CharField(default='caption', max_length=500),
        ),
        migrations.AddField(
            model_name='articles',
            name='img9cap',
            field=models.CharField(default='caption', max_length=500),
        ),
    ]
