# Generated by Django 2.0.5 on 2018-05-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='Thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
