# Generated by Django 2.0.5 on 2018-05-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20180524_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='imgs0',
            new_name='0',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='imgs1',
            new_name='1',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='imgs2',
            new_name='2',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='imgs3',
            new_name='3',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='imgs4',
            new_name='4',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='imgs5',
            new_name='5',
        ),
        migrations.AddField(
            model_name='cat',
            name='6',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='cat',
            name='7',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='cat',
            name='8',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='cat',
            name='9',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
