# Generated by Django 2.0.5 on 2018-05-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20180524_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='0',
            new_name='im0',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='1',
            new_name='im1',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='2',
            new_name='im2',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='3',
            new_name='im3',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='4',
            new_name='im4',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='5',
            new_name='im5',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='6',
            new_name='im6',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='7',
            new_name='im7',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='8',
            new_name='im8',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='9',
            new_name='im9',
        ),
    ]
