# Generated by Django 2.0.5 on 2018-05-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20180524_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='CatHead',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
