# Generated by Django 2.0.5 on 2018-05-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_cat_cathead'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='im0_setting',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='im1_setting',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='im2_setting',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='im3_setting',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='im4_setting',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='im5_setting',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='im6_setting',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='im7_setting',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='im8_setting',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='im9_setting',
            field=models.TextField(null=True),
        ),
    ]
