# Generated by Django 2.0.5 on 2018-05-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20180528_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='im0_head',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cat',
            name='im1_head',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cat',
            name='im2_head',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cat',
            name='im3_head',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cat',
            name='im4_head',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cat',
            name='im5_head',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cat',
            name='im6_head',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cat',
            name='im7_head',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cat',
            name='im8_head',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cat',
            name='im9_head',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
